### ISSUE TITLE
CeVIO CS7でIA,ONEが表示されない

### ISSUE THREAD

**Issue by ray45422** [ksasao/TTSController#11]
CeVIO CS7(64bit版)でIA, ONEが使用可能な音源として表示されません。

公式音源は `%ProgramW6432%\CeVIO\CeVIO Creative Studio (64bit)\Configuration\VocalSource\Talk` 以下にインストールされている音源情報が存在しますが、IA,ONEは`%ProgramW6432%\CeVIO\CeVIO Creative Studio\Configuration\VocalSource\Talk` に音源情報が存在するようです。

両方参照するようにしたところ動くみたいです。

**Comment by ksasao** [comment]
ご報告およびご提案ありがとうございます。挙動を確認し、修正を行いました。

**Comment by ray45422** [comment]
修正を確認しました。ありがとうございます。
