### ISSUE TITLE
実行プロセスと異なるアーキテクチャのVOICEROID2が使用可能として列挙される

### ISSUE THREAD

**Issue by ray45422** [ksasao/TTSController#8]
64bitプロセスで起動した際に32bitのVOICEROID2が使用可能として列挙される、またはその逆が起こります。
-  #7 で64bit版とA.I.VOICEについてインストール先が見つからない場合に列挙しない処理が追加されているのでそれと同様に追加しようと思いましたが 64689087dcc3ec6fe0e368d8adaa9eb44e4dcf40 でrevertされているためなにか問題があったのか気になっています。

**Comment by ksasao** [comment]
ご報告ありがとうございます。こちらでは再現できておらず、期待通りの動作をしてしまっているため、以下の情報をお知らせいただけますでしょうか。

- [ブラウザで音声合成する](https://github.com/ksasao/TTSController#%E3%83%96%E3%83%A9%E3%82%A6%E3%82%B6%E3%81%A7%E9%9F%B3%E5%A3%B0%E5%90%88%E6%88%90%E3%81%99%E3%82%8B)にあるビルド済み実行ファイル64bit版/32bit版のどちらを利用しても同様の現象が発生するか
  - 発生しない場合は最新のコードをご利用ください
- 発生する場合は、実行時のVOICEROID2 のインストール状態をお知らせください
  - 例：ビルド済み実行ファイル64bit版を動作させた場合に、VOICEROID2 32bit版→インストールされている、64bit版→インストールされていない

**Comment by ray45422** [comment]
- ビルド済み実行ファイルは64bit版を使用しても32bit版を使用してもVOICEROID2が列挙されます
  - エンジン名は64bit版は「VOICEROID64」、32bit版は「VOICEROID2」と表示されます

- VOICEROID2は32bit版のみがインストールされています

実行した際の画面を添付します

- 32bit版
![32](https://user-images.githubusercontent.com/8531031/179391404-90491e50-b6c3-4d32-8e25-1435fd42d923.png)
こちらは所持している音源全てが列挙されていて正しいです

- 64bit版
![64](https://user-images.githubusercontent.com/8531031/179391426-76592834-da72-4343-8056-23025a7f2de1.png)
VOICEROID2の64bit版はインストールされていないため列挙されるのは正しくありません。  
実際にVOICEROID2の64bit版を使用しようとした場合にはエラーが発生します。

- 手元で修正したものを #9 としてPRを作成しました

私は64bit版を知らなかったのですが、64bit版は32bit版と共存できるので基本的に問題ないということになるのでしょうか。
すみませんがご確認よろしくお願いします。

**Comment by ksasao** [comment]
詳細ありがとうございます。こちらでも再現できました。VOICEROID2 の 64bit 版はユーザー登録後サポートサイトからダウンロードする必要があるため、インストールしていないユーザーも多いと思われます。プルリクもマージさせていただきました。

**Comment by ray45422** [comment]
ありがとうございます！
これでcloseとさせていただきます。
